#!/bin/bash


#Assigning the arguments into a variable
DIRNAME=$1
ID=$2

#Exception to test if the inputs are empty
if [[ "$DIRNAME" = "" ]]; then 
    echo "You need to provide two arguments for this script to work. Please try again"
    exit

else 
    #Displaying Arguemnts given
    echo "Directiory name is: $1"
    echo "Indentifier name is: $2" 
fi
 
echo -e

echo "I am about to create a directory structure named ${DIRNAME}."

#Asking the user if they want to proceed
read -p "Do you want me to continue [Yes/no] " INPUT